#pragma once

#include "d_static/d_info.h"
#include <iterator>

namespace dDemoInfo
{

/**
 * Data structure for the hint movie list.
 */
struct OtehonInfo_s {
    SIZE_ASSERT(0x24);

    enum class Cond_e {
        NONE = 0,
        COIN_REQUIREMENT = 1,
        FINAL_BOSS_BEATEN = 2,
        GOAL_ALL = 3,
        COIN_ALL = 4,
        EXIT_ALL = 5,
        SPECIAL_WORLD_COMPLETE = 6,
        COIN_ALL_SPECIAL_WORLD = 7,
        GAME_COMPLETED = 8,
        WORLD_1_CLEAR = 9,
        WORLD_2_CLEAR = 10,
        WORLD_3_CLEAR = 11,
        WORLD_4_CLEAR = 12,
        WORLD_5_CLEAR = 13,
        WORLD_6_CLEAR = 14,
        WORLD_7_CLEAR = 15,
    };

    /* 0x00 */ int worldNo;
    /* 0x04 */ int stageNo;
    /* 0x08 */ int otehonType;
    /* 0x0C */ int nextGotoNo;
    /* 0x10 */ int otehonTime;
    /* 0x14 */ int courseNo;
    /* 0x18 */ int buyCoinCount;
    /* 0x1C */ Cond_e condition;
    /* 0x20 */ int conditionCoinCount = 0;
};

/**
 * Title screen demo stages.
 */
constexpr dInfo_c::StageNo_s c_titleDemoStage[] = {
  {WORLD_e::WORLD_1, STAGE_e::STAGE_4}, {WORLD_e::WORLD_1, STAGE_e::STAGE_6},
  {WORLD_e::WORLD_2, STAGE_e::STAGE_1}, {WORLD_e::WORLD_2, STAGE_e::STAGE_4},
  {WORLD_e::WORLD_3, STAGE_e::STAGE_1}, {WORLD_e::WORLD_3, STAGE_e::STAGE_5},
  {WORLD_e::WORLD_3, STAGE_e::TOWER},   {WORLD_e::WORLD_4, STAGE_e::STAGE_1},
  {WORLD_e::WORLD_4, STAGE_e::STAGE_5}, {WORLD_e::WORLD_5, STAGE_e::STAGE_4},
  {WORLD_e::WORLD_5, STAGE_e::STAGE_5}, {WORLD_e::WORLD_5, STAGE_e::GHOST_HOUSE},
  {WORLD_e::WORLD_6, STAGE_e::CASTLE},  {WORLD_e::WORLD_7, STAGE_e::STAGE_6},
  {WORLD_e::WORLD_8, STAGE_e::STAGE_7},
};
constexpr std::size_t c_titleDemoStageCnt = std::size(c_titleDemoStage);

constexpr OtehonInfo_s c_otehonInfo[] = {
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::NONE,

  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 4178,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::SPECIAL_WORLD_COMPLETE,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 7,
    .otehonTime = 1087,
    .courseNo = 1,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 5,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 32,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::GOAL_ALL,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::WORLD_1_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::TOWER),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 2837,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 10,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_1),
    .stageNo = static_cast<int>(STAGE_e::STAGE_5),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 30,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 32,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 15,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::GOAL_ALL,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 32,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 95,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 1731,
    .courseNo = 2,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 150,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::EXIT_ALL,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_4),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 14,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 20,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_5),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 3,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::WORLD_2_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_5),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 215,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_2),
    .stageNo = static_cast<int>(STAGE_e::STAGE_6),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 1,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 10,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 25,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 32,
    .otehonTime = 910,
    .courseNo = 1,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 65,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 35,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 165,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 9910,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 190,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 2,
    .otehonTime = 898,
    .courseNo = 2,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 40,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 5,
    .otehonTime = 1241,
    .courseNo = 2,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::WORLD_3_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 195,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::GHOST_HOUSE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 1,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 140,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_3),
    .stageNo = static_cast<int>(STAGE_e::STAGE_5),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 130,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 3290,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 45,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 2550,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 175,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::GAME_COMPLETED,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 125,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::WORLD_4_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::TOWER),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 4,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 10,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 70,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::STAGE_4),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 5,
    .otehonTime = 2340,
    .courseNo = 1,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 50,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::GHOST_HOUSE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 60,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_4),
    .stageNo = static_cast<int>(STAGE_e::CASTLE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 3170,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 145,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_5),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 7,
    .otehonTime = 4096,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 105,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_5),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 1760,
    .courseNo = 2,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 55,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_5),
    .stageNo = static_cast<int>(STAGE_e::GHOST_HOUSE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 0,
    .otehonTime = 1299,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 75,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_5),
    .stageNo = static_cast<int>(STAGE_e::GHOST_HOUSE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::FINAL_BOSS_BEATEN,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_5),
    .stageNo = static_cast<int>(STAGE_e::CASTLE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 3231,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::WORLD_5_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 6,
    .otehonTime = 2626,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 80,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 32,
    .otehonTime = 4006,
    .courseNo = 3,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 135,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 2,
    .otehonTime = 1096,
    .courseNo = 1,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 85,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 205,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::STAGE_5),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 32,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 90,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::STAGE_6),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 3,
    .otehonTime = 14400,
    .courseNo = 1,
    .buyCoinCount = 10,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 100,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_6),
    .stageNo = static_cast<int>(STAGE_e::CASTLE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 2,
    .otehonTime = 2157,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::WORLD_6_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_7),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::WORLD_7_CLEAR,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_7),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 6,
    .otehonTime = 1878,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 170,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_7),
    .stageNo = static_cast<int>(STAGE_e::TOWER),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 160,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_7),
    .stageNo = static_cast<int>(STAGE_e::GHOST_HOUSE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 120,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_7),
    .stageNo = static_cast<int>(STAGE_e::STAGE_4),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 32,
    .otehonTime = 5151,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::COIN_ALL_SPECIAL_WORLD,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_7),
    .stageNo = static_cast<int>(STAGE_e::CASTLE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 32,
    .otehonTime = 2282,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 115,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_8),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SECRET_EXIT),
    .nextGotoNo = 32,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::FINAL_BOSS_BEATEN,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_8),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 180,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_8),
    .stageNo = static_cast<int>(STAGE_e::TOWER),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 32,
    .otehonTime = 1547,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 110,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_8),
    .stageNo = static_cast<int>(STAGE_e::DOOMSHIP),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 4280,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 155,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_8),
    .stageNo = static_cast<int>(STAGE_e::CASTLE),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 25200,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::EXIT_ALL,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_1),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 225,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_2),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 220,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::ENDLESS_1UPS),
    .nextGotoNo = 0,
    .otehonTime = 2170,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 185,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_3),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 210,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_4),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 1,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::SPECIAL_WORLD_COMPLETE,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_5),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 5,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 230,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_6),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::STAR_COIN),
    .nextGotoNo = 1,
    .otehonTime = 1145,
    .courseNo = 0,
    .buyCoinCount = 0,
    .condition = OtehonInfo_s::Cond_e::COIN_REQUIREMENT,
    .conditionCoinCount = 200,
  },
  {
    .worldNo = static_cast<int>(WORLD_e::WORLD_9),
    .stageNo = static_cast<int>(STAGE_e::STAGE_7),
    .otehonType = static_cast<int>(dInfo_c::OtehonType_e::SUPER_SKILLS),
    .nextGotoNo = 0,
    .otehonTime = 14400,
    .courseNo = 0,
    .buyCoinCount = 3,
    .condition = OtehonInfo_s::Cond_e::GAME_COMPLETED,
  },
};
constexpr std::size_t c_otehonInfoCnt = std::size(c_otehonInfo);

}; // namespace dDemoInfo
